
export interface Country {
    code: string;
    name: string;
    phoneCode: string;
    unitSystem: 'metric' | 'imperial';
    biomarkerUnit: 'conventional' | 'si';
    dateFormat: string;
}

export const dateFormats = [
    { format: 'MM-dd-yyyy', label: 'MM-DD-YYYY' },
    { format: 'dd-MM-yyyy', label: 'DD-MM-YYYY' },
    { format: 'yyyy-MM-dd', label: 'YYYY-MM-DD' },
    { format: 'dd.MM.yyyy', label: 'DD.MM.YYYY' },
    { format: 'dd/MM/yyyy', label: 'DD/MM/YYYY' },
    { format: 'yyyy/MM/dd', label: 'YYYY/MM/DD' },
    { format: 'PPP', label: 'Month D, YYYY' },
]

export const countries: Country[] = [
    { code: 'IN', name: 'India', phoneCode: '+91', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'dd-MM-yyyy' },
    { code: 'AF', name: 'Afghanistan', phoneCode: '+93', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'AL', name: 'Albania', phoneCode: '+355', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'DZ', name: 'Algeria', phoneCode: '+213', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'AD', name: 'Andorra', phoneCode: '+376', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'AO', name: 'Angola', phoneCode: '+244', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'AG', name: 'Antigua and Barbuda', phoneCode: '+1-268', unitSystem: 'imperial', biomarkerUnit: 'conventional', dateFormat: 'dd-MM-yyyy' },
    { code: 'AR', name: 'Argentina', phoneCode: '+54', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'dd/MM/yyyy' },
    { code: 'AM', name: 'Armenia', phoneCode: '+374', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'AU', name: 'Australia', phoneCode: '+61', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd-MM-yyyy' },
    { code: 'AT', name: 'Austria', phoneCode: '+43', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd.MM.yyyy' },
    { code: 'AZ', name: 'Azerbaijan', phoneCode: '+994', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'BS', name: 'Bahamas', phoneCode: '+1-242', unitSystem: 'imperial', biomarkerUnit: 'conventional', dateFormat: 'dd-MM-yyyy' },
    { code: 'BH', name: 'Bahrain', phoneCode: '+973', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'BD', name: 'Bangladesh', phoneCode: '+880', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'dd-MM-yyyy' },
    { code: 'BB', name: 'Barbados', phoneCode: '+1-246', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd-MM-yyyy' },
    { code: 'BY', name: 'Belarus', phoneCode: '+375', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd.MM.yyyy' },
    { code: 'BE', name: 'Belgium', phoneCode: '+32', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd/MM/yyyy' },
    { code: 'BZ', name: 'Belize', phoneCode: '+501', unitSystem: 'imperial', biomarkerUnit: 'conventional', dateFormat: 'dd-MM-yyyy' },
    { code: 'BJ', name: 'Benin', phoneCode: '+229', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'BT', name: 'Bhutan', phoneCode: '+975', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'yyyy-MM-dd' },
    { code: 'BO', name: 'Bolivia', phoneCode: '+591', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'dd-MM-yyyy' },
    { code: 'BA', name: 'Bosnia and Herzegovina', phoneCode: '+387', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'BW', name: 'Botswana', phoneCode: '+267', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'BR', name: 'Brazil', phoneCode: '+55', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'dd/MM/yyyy' },
    { code: 'BN', name: 'Brunei', phoneCode: '+673', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'BG', name: 'Bulgaria', phoneCode: '+359', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'BF', name: 'Burkina Faso', phoneCode: '+226', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'BI', name: 'Burundi', phoneCode: '+257', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'CV', name: 'Cabo Verde', phoneCode: '+238', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'KH', name: 'Cambodia', phoneCode: '+855', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'yyyy-MM-dd' },
    { code: 'CM', name: 'Cameroon', phoneCode: '+237', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'CA', name: 'Canada', phoneCode: '+1', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'CF', name: 'Central African Republic', phoneCode: '+236', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'TD', name: 'Chad', phoneCode: '+235', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'CL', name: 'Chile', phoneCode: '+56', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'dd-MM-yyyy' },
    { code: 'CN', name: 'China', phoneCode: '+86', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'yyyy-MM-dd' },
    { code: 'CO', name: 'Colombia', phoneCode: '+57', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'dd/MM/yyyy' },
    { code: 'KM', name: 'Comoros', phoneCode: '+269', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'CG', name: 'Congo', phoneCode: '+242', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'CD', name: 'Congo, Democratic Republic of the', phoneCode: '+243', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'CR', name: 'Costa Rica', phoneCode: '+506', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'dd/MM/yyyy' },
    { code: 'HR', name: 'Croatia', phoneCode: '+385', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd.MM.yyyy.' },
    { code: 'CU', name: 'Cuba', phoneCode: '+53', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'dd/MM/yyyy' },
    { code: 'CY', name: 'Cyprus', phoneCode: '+357', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd/MM/yyyy' },
    { code: 'CZ', name: 'Czech Republic', phoneCode: '+420', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd.MM.yyyy' },
    { code: 'CI', name: 'Côte d\'Ivoire', phoneCode: '+225', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'DK', name: 'Denmark', phoneCode: '+45', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd-MM-yyyy' },
    { code: 'DJ', name: 'Djibouti', phoneCode: '+253', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'DM', name: 'Dominica', phoneCode: '+1-767', unitSystem: 'imperial', biomarkerUnit: 'conventional', dateFormat: 'dd-MM-yyyy' },
    { code: 'DO', name: 'Dominican Republic', phoneCode: '+1-809', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'dd-MM-yyyy' },
    { code: 'EC', name: 'Ecuador', phoneCode: '+593', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'dd/MM/yyyy' },
    { code: 'EG', name: 'Egypt', phoneCode: '+20', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'dd/MM/yyyy' },
    { code: 'SV', name: 'El Salvador', phoneCode: '+503', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'dd/MM/yyyy' },
    { code: 'GQ', name: 'Equatorial Guinea', phoneCode: '+240', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'ER', name: 'Eritrea', phoneCode: '+291', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'EE', name: 'Estonia', phoneCode: '+372', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd.MM.yyyy' },
    { code: 'SZ', name: 'Eswatini', phoneCode: '+268', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'ET', name: 'Ethiopia', phoneCode: '+251', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'dd/MM/yyyy' },
    { code: 'FJ', name: 'Fiji', phoneCode: '+679', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd/MM/yyyy' },
    { code: 'FI', name: 'Finland', phoneCode: '+358', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'd.M.yyyy' },
    { code: 'FR', name: 'France', phoneCode: '+33', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd/MM/yyyy' },
    { code: 'GA', name: 'Gabon', phoneCode: '+241', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'GM', name: 'Gambia', phoneCode: '+220', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'GE', name: 'Georgia', phoneCode: '+995', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'DE', name: 'Germany', phoneCode: '+49', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd.MM.yyyy' },
    { code: 'GH', name: 'Ghana', phoneCode: '+233', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd/MM/yyyy' },
    { code: 'GR', name: 'Greece', phoneCode: '+30', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd/MM/yyyy' },
    { code: 'GD', name: 'Grenada', phoneCode: '+1-473', unitSystem: 'imperial', biomarkerUnit: 'conventional', dateFormat: 'dd-MM-yyyy' },
    { code: 'GT', name: 'Guatemala', phoneCode: '+502', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'd/MM/yyyy' },
    { code: 'GN', name: 'Guinea', phoneCode: '+224', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'GW', name: 'Guinea-Bissau', phoneCode: '+245', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'GY', name: 'Guyana', phoneCode: '+592', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'HT', name: 'Haiti', phoneCode: '+509', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'dd/MM/yyyy' },
    { code: 'HN', name: 'Honduras', phoneCode: '+504', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'MM-dd-yyyy' },
    { code: 'HU', name: 'Hungary', phoneCode: '+36', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy. MM. dd.' },
    { code: 'IS', name: 'Iceland', phoneCode: '+354', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'd.M.yyyy' },
    { code: 'ID', name: 'Indonesia', phoneCode: '+62', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'dd/MM/yyyy' },
    { code: 'IR', name: 'Iran', phoneCode: '+98', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'yyyy/MM/dd' },
    { code: 'IQ', name: 'Iraq', phoneCode: '+964', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'dd/MM/yyyy' },
    { code: 'IE', name: 'Ireland', phoneCode: '+353', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd/MM/yyyy' },
    { code: 'IL', name: 'Israel', phoneCode: '+972', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'dd/MM/yyyy' },
    { code: 'IT', name: 'Italy', phoneCode: '+39', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd/MM/yyyy' },
    { code: 'JM', name: 'Jamaica', phoneCode: '+1-876', unitSystem: 'imperial', biomarkerUnit: 'conventional', dateFormat: 'dd-MM-yyyy' },
    { code: 'JP', name: 'Japan', phoneCode: '+81', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'yyyy-MM-dd' },
    { code: 'JO', name: 'Jordan', phoneCode: '+962', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'yyyy-MM-dd' },
    { code: 'KZ', name: 'Kazakhstan', phoneCode: '+7', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd.MM.yyyy' },
    { code: 'KE', name: 'Kenya', phoneCode: '+254', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd/MM/yyyy' },
    { code: 'KI', name: 'Kiribati', phoneCode: '+686', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd/MM/yyyy' },
    { code: 'KW', name: 'Kuwait', phoneCode: '+965', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'yyyy-MM-dd' },
    { code: 'KG', name: 'Kyrgyzstan', phoneCode: '+996', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd.MM.yyyy' },
    { code: 'LA', name: 'Laos', phoneCode: '+856', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'dd/MM/yyyy' },
    { code: 'LV', name: 'Latvia', phoneCode: '+371', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd.MM.yyyy.' },
    { code: 'LB', name: 'Lebanon', phoneCode: '+961', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'dd/MM/yyyy' },
    { code: 'LS', name: 'Lesotho', phoneCode: '+266', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'LR', name: 'Liberia', phoneCode: '+231', unitSystem: 'imperial', biomarkerUnit: 'conventional', dateFormat: 'dd-MM-yyyy' },
    { code: 'LY', name: 'Libya', phoneCode: '+218', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'dd-MM-yyyy' },
    { code: 'LI', name: 'Liechtenstein', phoneCode: '+423', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd.MM.yyyy' },
    { code: 'LT', name: 'Lithuania', phoneCode: '+370', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'LU', name: 'Luxembourg', phoneCode: '+352', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd.MM.yyyy' },
    { code: 'MG', name: 'Madagascar', phoneCode: '+261', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd/MM/yyyy' },
    { code: 'MW', name: 'Malawi', phoneCode: '+265', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd/MM/yyyy' },
    { code: 'MY', name: 'Malaysia', phoneCode: '+60', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'dd/MM/yyyy' },
    { code: 'MV', name: 'Maldives', phoneCode: '+960', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'dd/MM/yyyy' },
    { code: 'ML', name: 'Mali', phoneCode: '+223', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'MT', name: 'Malta', phoneCode: '+356', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd/MM/yyyy' },
    { code: 'MH', name: 'Marshall Islands', phoneCode: '+692', unitSystem: 'imperial', biomarkerUnit: 'conventional', dateFormat: 'MM-dd-yyyy' },
    { code: 'MR', name: 'Mauritania', phoneCode: '+222', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'MU', name: 'Mauritius', phoneCode: '+230', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd/MM/yyyy' },
    { code: 'MX', name: 'Mexico', phoneCode: '+52', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'dd/MM/yyyy' },
    { code: 'FM', name: 'Micronesia', phoneCode: '+691', unitSystem: 'imperial', biomarkerUnit: 'conventional', dateFormat: 'MM-dd-yyyy' },
    { code: 'MD', name: 'Moldova', phoneCode: '+373', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd.MM.yyyy' },
    { code: 'MC', name: 'Monaco', phoneCode: '+377', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd/MM/yyyy' },
    { code: 'MN', name: 'Mongolia', phoneCode: '+976', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy.MM.dd' },
    { code: 'ME', name: 'Montenegro', phoneCode: '+382', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'd.M.yyyy.' },
    { code: 'MA', name: 'Morocco', phoneCode: '+212', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd-MM-yyyy' },
    { code: 'MZ', name: 'Mozambique', phoneCode: '+258', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd/MM/yyyy' },
    { code: 'MM', name: 'Myanmar', phoneCode: '+95', unitSystem: 'imperial', biomarkerUnit: 'conventional', dateFormat: 'dd-MM-yyyy' },
    { code: 'NA', name: 'Namibia', phoneCode: '+264', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd/MM/yyyy' },
    { code: 'NR', name: 'Nauru', phoneCode: '+674', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd/MM/yyyy' },
    { code: 'NP', name: 'Nepal', phoneCode: '+977', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'yyyy-MM-dd' },
    { code: 'NL', name: 'Netherlands', phoneCode: '+31', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd-MM-yyyy' },
    { code: 'NZ', name: 'New Zealand', phoneCode: '+64', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'd/MM/yyyy' },
    { code: 'NI', name: 'Nicaragua', phoneCode: '+505', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'dd-MM-yyyy' },
    { code: 'NE', name: 'Niger', phoneCode: '+227', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'NG', name: 'Nigeria', phoneCode: '+234', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd/MM/yyyy' },
    { code: 'KP', name: 'North Korea', phoneCode: '+850', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'yyyy. M. d' },
    { code: 'MK', name: 'North Macedonia', phoneCode: '+389', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'd.M.yyyy' },
    { code: 'NO', name: 'Norway', phoneCode: '+47', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd.MM.yyyy' },
    { code: 'OM', name: 'Oman', phoneCode: '+968', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'yyyy-MM-dd' },
    { code: 'PK', name: 'Pakistan', phoneCode: '+92', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'dd-MM-yy' },
    { code: 'PW', name: 'Palau', phoneCode: '+680', unitSystem: 'imperial', biomarkerUnit: 'conventional', dateFormat: 'MM/dd/yyyy' },
    { code: 'PA', name: 'Panama', phoneCode: '+507', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'MM/dd/yyyy' },
    { code: 'PG', name: 'Papua New Guinea', phoneCode: '+675', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd/MM/yyyy' },
    { code: 'PY', name: 'Paraguay', phoneCode: '+595', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'dd/MM/yyyy' },
    { code: 'PE', name: 'Peru', phoneCode: '+51', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'dd/MM/yyyy' },
    { code: 'PH', name: 'Philippines', phoneCode: '+63', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'M/d/yyyy' },
    { code: 'PL', name: 'Poland', phoneCode: '+48', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd.MM.yyyy' },
    { code: 'PT', name: 'Portugal', phoneCode: '+351', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd-MM-yyyy' },
    { code: 'QA', name: 'Qatar', phoneCode: '+974', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'yyyy-MM-dd' },
    { code: 'RO', name: 'Romania', phoneCode: '+40', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd.MM.yyyy' },
    { code: 'RU', name: 'Russia', phoneCode: '+7', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd.MM.yyyy' },
    { code: 'RW', name: 'Rwanda', phoneCode: '+250', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'KN', name: 'Saint Kitts and Nevis', phoneCode: '+1-869', unitSystem: 'imperial', biomarkerUnit: 'conventional', dateFormat: 'dd-MM-yyyy' },
    { code: 'LC', name: 'Saint Lucia', phoneCode: '+1-758', unitSystem: 'imperial', biomarkerUnit: 'conventional', dateFormat: 'dd-MM-yyyy' },
    { code: 'VC', name: 'Saint Vincent and the Grenadines', phoneCode: '+1-784', unitSystem: 'imperial', biomarkerUnit: 'conventional', dateFormat: 'dd-MM-yyyy' },
    { code: 'WS', name: 'Samoa', phoneCode: '+685', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd/MM/yyyy' },
    { code: 'SM', name: 'San Marino', phoneCode: '+378', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd/MM/yyyy' },
    { code: 'ST', name: 'Sao Tome and Principe', phoneCode: '+239', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'SA', name: 'Saudi Arabia', phoneCode: '+966', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'dd/MM/yyyy' },
    { code: 'SN', name: 'Senegal', phoneCode: '+221', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd-MM-yyyy' },
    { code: 'RS', name: 'Serbia', phoneCode: '+381', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'd.M.yyyy.' },
    { code: 'SC', name: 'Seychelles', phoneCode: '+248', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd-MM-yyyy' },
    { code: 'SL', name: 'Sierra Leone', phoneCode: '+232', unitSystem: 'imperial', biomarkerUnit: 'conventional', dateFormat: 'dd-MM-yyyy' },
    { code: 'SG', name: 'Singapore', phoneCode: '+65', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'd/M/yyyy' },
    { code: 'SK', name: 'Slovakia', phoneCode: '+421', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'd. M. yyyy' },
    { code: 'SI', name: 'Slovenia', phoneCode: '+386', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'd. MM. yyyy' },
    { code: 'SB', name: 'Solomon Islands', phoneCode: '+677', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd/MM/yyyy' },
    { code: 'SO', name: 'Somalia', phoneCode: '+252', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd-MM-yyyy' },
    { code: 'ZA', name: 'South Africa', phoneCode: '+27', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy/MM/dd' },
    { code: 'KR', name: 'South Korea', phoneCode: '+82', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'yyyy. MM. dd.' },
    { code: 'SS', name: 'South Sudan', phoneCode: '+211', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd/MM/yyyy' },
    { code: 'ES', name: 'Spain', phoneCode: '+34', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd/MM/yyyy' },
    { code: 'LK', name: 'Sri Lanka', phoneCode: '+94', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'yyyy-MM-dd' },
    { code: 'SD', name: 'Sudan', phoneCode: '+249', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'dd/MM/yyyy' },
    { code: 'SR', name: 'Suriname', phoneCode: '+597', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd-MM-yyyy' },
    { code: 'SE', name: 'Sweden', phoneCode: '+46', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'yyyy-MM-dd' },
    { code: 'CH', name: 'Switzerland', phoneCode: '+41', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd.MM.yyyy' },
    { code: 'SY', name: 'Syria', phoneCode: '+963', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'dd/MM/yyyy' },
    { code: 'TW', name: 'Taiwan', phoneCode: '+886', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'yyyy/M/d' },
    { code: 'TJ', name: 'Tajikistan', phoneCode: '+992', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd.MM.yyyy' },
    { code: 'TZ', name: 'Tanzania', phoneCode: '+255', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd/MM/yyyy' },
    { code: 'TH', name: 'Thailand', phoneCode: '+66', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'd/M/yyyy' },
    { code: 'TL', name: 'Timor-Leste', phoneCode: '+670', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd-MM-yyyy' },
    { code: 'TG', name: 'Togo', phoneCode: '+228', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd-MM-yyyy' },
    { code: 'TO', name: 'Tonga', phoneCode: '+676', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd/MM/yyyy' },
    { code: 'TT', name: 'Trinidad and Tobago', phoneCode: '+1-868', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd/MM/yyyy' },
    { code: 'TN', name: 'Tunisia', phoneCode: '+216', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd-MM-yyyy' },
    { code: 'TR', name: 'Turkey', phoneCode: '+90', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd.MM.yyyy' },
    { code: 'TM', name: 'Turkmenistan', phoneCode: '+993', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd.MM.yy' },
    { code: 'TV', name: 'Tuvalu', phoneCode: '+688', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd/MM/yyyy' },
    { code: 'UG', name: 'Uganda', phoneCode: '+256', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd/MM/yyyy' },
    { code: 'UA', name: 'Ukraine', phoneCode: '+380', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd.MM.yyyy' },
    { code: 'AE', name: 'United Arab Emirates', phoneCode: '+971', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd/MM/yyyy' },
    { code: 'GB', name: 'United Kingdom', phoneCode: '+44', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd/MM/yyyy' },
    { code: 'US', name: 'United States', phoneCode: '+1', unitSystem: 'imperial', biomarkerUnit: 'conventional', dateFormat: 'MM-dd-yyyy' },
    { code: 'UY', name: 'Uruguay', phoneCode: '+598', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'dd/MM/yyyy' },
    { code: 'UZ', name: 'Uzbekistan', phoneCode: '+998', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd.MM.yyyy' },
    { code: 'VU', name: 'Vanuatu', phoneCode: '+678', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd/MM/yyyy' },
    { code: 'VE', name: 'Venezuela', phoneCode: '+58', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'dd/MM/yyyy' },
    { code: 'VN', name: 'Vietnam', phoneCode: '+84', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'dd/MM/yyyy' },
    { code: 'YE', name: 'Yemen', phoneCode: '+967', unitSystem: 'metric', biomarkerUnit: 'conventional', dateFormat: 'dd/MM/yyyy' },
    { code: 'ZM', name: 'Zambia', phoneCode: '+260', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd/MM/yyyy' },
    { code: 'ZW', name: 'Zimbabwe', phoneCode: '+263', unitSystem: 'metric', biomarkerUnit: 'si', dateFormat: 'dd/MM/yyyy' },
];
